// Package sdk provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package sdk

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// CreateSecret defines model for CreateSecret.
type CreateSecret struct {
	// RecipientIds A list of recipient IDs.
	RecipientIds []string `json:"recipient_ids"`

	// Reference A reference string for the secret.
	Reference string `json:"reference"`
}

// CreateSecretResponse defines model for CreateSecretResponse.
type CreateSecretResponse struct {
	S3Info *struct {
		Fields *struct {
			Key                  *string   `json:"key,omitempty"`
			Policy               *string   `json:"policy,omitempty"`
			XAmzAlgorithm        *string   `json:"x-amz-algorithm,omitempty"`
			XAmzCredential       *string   `json:"x-amz-credential,omitempty"`
			XAmzDate             *string   `json:"x-amz-date,omitempty"`
			XAmzMetaRecipientIds *[]string `json:"x-amz-meta-recipient_ids,omitempty"`
			XAmzMetaReference    *string   `json:"x-amz-meta-reference,omitempty"`
			XAmzMetaSenderId     *string   `json:"x-amz-meta-sender_id,omitempty"`
			XAmzSignature        *string   `json:"x-amz-signature,omitempty"`
		} `json:"fields,omitempty"`
		Url *string `json:"url,omitempty"`
	} `json:"s3_info,omitempty"`
	Users *[]User `json:"users,omitempty"`
}

// GeneralErrorResponse defines model for GeneralErrorResponse.
type GeneralErrorResponse struct {
	Message string `json:"message"`
}

// Key defines model for Key.
type Key struct {
	CreatedAt  *string             `json:"created_at,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	KeyData    *string             `json:"key_data,omitempty"`
	Reference  *string             `json:"reference,omitempty"`
	Thumbprint *string             `json:"thumbprint,omitempty"`
}

// NewKey defines model for NewKey.
type NewKey struct {
	Force      *bool   `json:"force,omitempty"`
	KeyData    *string `json:"key_data,omitempty"`
	Only       *bool   `json:"only,omitempty"`
	Reference  *string `json:"reference,omitempty"`
	Thumbprint *string `json:"thumbprint,omitempty"`
}

// Secret defines model for Secret.
type Secret struct {
	Recipient *string `json:"recipient,omitempty"`
	Reference *string `json:"reference,omitempty"`
	Sender    *string `json:"sender,omitempty"`
	SentAt    *string `json:"sent_at,omitempty"`
	Size      *string `json:"size,omitempty"`
}

// User defines model for User.
type User struct {
	Email     *string             `json:"email,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Keys      *[]Key              `json:"keys,omitempty"`
	Shortcode *string             `json:"shortcode,omitempty"`
}

// GeneralResponse defines model for GeneralResponse.
type GeneralResponse = GeneralErrorResponse

// Keys defines model for Keys.
type Keys = []Key

// Secrets defines model for Secrets.
type Secrets = []Secret

// Users defines model for Users.
type Users = []User

// DeleteSecretParams defines parameters for DeleteSecret.
type DeleteSecretParams struct {
	Reference *string `form:"reference,omitempty" json:"reference,omitempty"`
}

// GetSecretParams defines parameters for GetSecret.
type GetSecretParams struct {
	Reference *string `form:"reference,omitempty" json:"reference,omitempty"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	Id *[]string `form:"id,omitempty" json:"id,omitempty"`
}

// PostSecretJSONRequestBody defines body for PostSecret for application/json ContentType.
type PostSecretJSONRequestBody = CreateSecret

// PostUserMeKeyJSONRequestBody defines body for PostUserMeKey for application/json ContentType.
type PostUserMeKeyJSONRequestBody = NewKey

// PostUserUserIdKeyJSONRequestBody defines body for PostUserUserIdKey for application/json ContentType.
type PostUserUserIdKeyJSONRequestBody = NewKey

// DeleteUserUserIdKeyKeyIdKeyJSONRequestBody defines body for DeleteUserUserIdKeyKeyIdKey for application/json ContentType.
type DeleteUserUserIdKeyKeyIdKeyJSONRequestBody = Key

// GetUserUserIdKeyKeyIdKeyJSONRequestBody defines body for GetUserUserIdKeyKeyIdKey for application/json ContentType.
type GetUserUserIdKeyKeyIdKeyJSONRequestBody = Key
